INSERT INTO user_type (type_name) VALUES ('Admin');
INSERT INTO user_type (type_name) VALUES ('Client');
INSERT INTO user (user_type_id, email, password, first_name, last_name) VALUES (1,'admin@gmail.com','d0133e212ae3148aeb516610fc211410aec1358510c14da997', 'Admin', 'Admin');
INSERT INTO activity (description) VALUES ('Reading');
INSERT INTO activity (description) VALUES ('Swimming');
INSERT INTO activity (description) VALUES ('Study');
INSERT INTO activity (description) VALUES ('Riding a bike');
INSERT INTO activity (description) VALUES ('Driving a car');
INSERT INTO activity (description) VALUES ('Sleep');
INSERT INTO activity (description) VALUES ('Eat');
INSERT INTO language (language_name, language_code) VALUES ('English', 'en');
INSERT INTO language (language_name, language_code) VALUES ('Ukrainian', 'ua');
INSERT INTO language (language_name, language_code) VALUES ('Russian', 'ru');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 1,'Reading');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 1,'Читання');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 1,'Читание');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 2,'Swimming');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 2,'Плавання');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 2,'Плавание');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 3,'Study');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 3,'Навчання');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 3,'Учеба');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 4,'Riding a bike');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 4,'Велосипедна їзда');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 4,'Езда на велосипеде');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 5,'Driving a car');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 5,'Водіння авто');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 5,'Вождение авто');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 6,'Sleep');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 6,'Сон');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 6,'Сон');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (1, 7,'Eat');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (2, 7,'Прийом їжі');
INSERT INTO activity_translate (language_id, activity_id, description)  VALUES (3, 7,'Приём пищи');